### ISSUE TITLE
[Compose] Support for Android library modules?

### ISSUE THREAD

**Issue by adctdoherty** [figma/code-connect#282]
OS: MacOS Sonoma 14.5
CLI versions:
```bash
% npx --version
10.9.2
% npx figma -V
1.3.4
```

libs.versions.toml
```toml
[versions]
agp = "8.6.1"
codeConnectLib = "1.1.3"
figmaCodeConnect = "1.2.1"
kotlin = "2.0.21"

[libraries]
code-connect-lib = { module = "com.figma.code.connect:code-connect-lib", version.ref = "codeConnectLib" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
figma-code-connect = { id = "com.figma.code.connect", version.ref = "figmaCodeConnect" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
```

basicLibrary/build.gradle.kts
```kts
plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.figma.code.connect)
}

android {
    // [...]
}

dependencies {
    implementation(libs.code.connect.lib)
}
```

figma.config.json:
```json
{
  "codeConnect": {
    "parser": "compose",
    "include": ["app/src/main/**/*.kt", "basiclibrary/src/main/**/*.kt"]
  }
}
```

I get a parsing error applying Code Connect Compose plugin and library in an Android library:
```bash
 % npx figma connect --verbose              
{ ... }
Trace: Error: Parser exited with code 1
    at ChildProcess.<anonymous> (/Users/tdoherty/.nvm/versions/node/v22.15.0/lib/node_modules/@figma/code-connect/dist/connect/parser_executables.js:112:32)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:351:12)
    at getCodeConnectObjects (/Users/tdoherty/.nvm/versions/node/v22.15.0/lib/node_modules/@figma/code-connect/dist/commands/connect.js:182:25)
    at async getUnconnectedComponentsAndConnectedComponentMappings (/Users/tdoherty/.nvm/versions/node/v22.15.0/lib/node_modules/@figma/code-connect/dist/connect/wizard/run_wizard.js:536:32)
    at async runWizard (/Users/tdoherty/.nvm/versions/node/v22.15.0/lib/node_modules/@figma/code-connect/dist/connect/wizard/run_wizard.js:785:68)
Error calling parser: Error: Parser exited with code 1.
```

It _does_ work when Code Connect is only being applied to the application module.
